### ISSUE TITLE
proxyConsole 的问题

### ISSUE THREAD

**Issue by mtdpcs** [gomeplusFED/GER#1]
在proxy.js 中reportConsole这个方法 typeList的长度永远不可能大于10啊
       let typeList = this.consoleList[ type ];
        typeList = typeList || [];
        typeList.push(
            utils.assignObject( utils.getSystemParams(), {
                msg: msg,
                level: level,
                rowNum: '',
                colNum: '',
                targetUrl: ''
            } )
        );
        if ( typeList.length > 10 ) {
            this.errorQueue = this.errorQueue.concat( typeList );
            this.send( true, () => {
                typeList = [];
            } );
        }

**Comment by xiaojue** [comment]
看了一下代码，应该是每次调用reportConsole的时候，也就是console.log的时候都会往consoleList[type]里push一个错误，然后大于10的时候再去send，这里其实proxy的功能目前bug还比较多，建议慎用proxy功能，这里我回去真实情况测试下。
