### ISSUE TITLE
【前辈，请教个问题，还请空闲的时候可以解答下】这里为什么要这样使用

### ISSUE THREAD

**Issue by AsherSun** [gomeplusFED/GER#4]
https://github.com/gomeplusFED/GER/blob/12b2e4d75f87116983ce198e9a575c95631fb658/src/lib/proxy.js#L131

代码如上，我不太清楚的是，这里不使用 apply 来调用改方法也是可以的，还请前辈解答下这里为什么要使用apply 来调用方法

**Comment by AsherSun** [comment]
@xiaojue @qifeng0748 @Youjingyu @zdongh2016

**Comment by Youjingyu** [comment]
@AsherSun 你去看看 apply 的作用呀

**Comment by AsherSun** [comment]
前辈，<code>apply</code>的作用与概念我还是理解一些的。并且js中的<code>this</code>指针并不会在 <code>js function</code> 声明的时候绑定，而是在<code>function </code>被调用的时候绑定

<code>apply</code> 改变了 当前 <code>func</code> 方法的调用，但是<code>func</code>的调用由当前的<code>this</code> 也就是<code>proxy</code> 调用是合理的吗？

因为我根据当前的代码上下文得知，<code>func</code> 的方法是上一步中的<code>window.console[key]</code> 的方法。所以这里的使用<code>apply</code>改变<code>func</code>的调用，传入的调用对象为 <code>window.console</code> 是否会更合理一些？

其次，<code>func</code>即使不使用<code>apply</code>来改变调用对象也是可以的。我不太理解为什么会把调用对象改变为 <code>this</code> 也就是<code>proxy</code>

**代码上下文**
https://github.com/gomeplusFED/GER/blob/12b2e4d75f87116983ce198e9a575c95631fb658/src/lib/proxy.js#L99-L132

请大佬解答下为什么 <code> return func.apply( this, args ); </code>传入的调用对象是 <code> this</code>。非常感谢

**Comment by xiaojue** [comment]
@AsherSun 关注点在apply的第二个参数，而不是作用域。
