### ISSUE TITLE
【前辈，请教个问题】在什么情况下，传入的参数会是一个字符串？所以这里的写法意义何在呀？

### ISSUE THREAD

**Issue by AsherSun** [gomeplusFED/GER#5]
https://github.com/gomeplusFED/GER/blob/12b2e4d75f87116983ce198e9a575c95631fb658/src/lib/proxy.js#L217-L223

### 疑问
+ 什么情况下，传入的参数是一个字符串？
+ 如果没有传入字符串的情况，那么这段代码是否没有意义？

还请前辈解答下，谢谢🙏

**Comment by AsherSun** [comment]
@xiaojue @qifeng0748 @Youjingyu @zdongh2016

**Comment by Youjingyu** [comment]
@AsherSun 支持用字符串来声明函数，你可以看看  js 的 Function 构造函数[Function](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function)

**Comment by AsherSun** [comment]
前辈，在问问题之前我已经查阅过 Function 构造函数的文档了。但是 这段代码的上下文语义 <code>cb</code> 回调函数是<code>js</code>中定时器的参数。于是我在浏览器控制台中写入
```javascript
setTimeout('console.log(1)', 1000);
```
控制台抛错，由此证明<code>js</code>的定时器的参数并不支持字符串声明的函数

**程序运行结果**
![image](https://user-images.githubusercontent.com/28916706/67541207-b4709c00-f71a-11e9-9719-ded131d8d26c.png)

**代码上下文**

https://github.com/gomeplusFED/GER/blob/12b2e4d75f87116983ce198e9a575c95631fb658/src/lib/proxy.js#L212-L231

**Comment by qifeng0748** [comment]
@AsherSun 看你截图是在 github 页面中打开的控制台，然后报错。
要学会**看报错内容**说的是什么意思，再下结论。
那么我们首先看看你截图里的报错是什么意思。

> Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src github.githubassets.com".

这里有一个关键的词 **unsafe-eval** 这是[CSP 策略指令](https://developer.mozilla.org/zh-CN/docs/Web/Security/CSP/CSP_policy_directives)中的知识。

上面的报错意思就是，因为未使用 `unsafe-eval` 关键字授权所以不能使用 `eval()` 方法，
`setTimeout()` 第一个参数如果是字符串，那么解析方式和 `eval()` 一样，结合上面的CSP策略解释，所以你在控制台执行就会报错。

你在其他页面或者自己写个 HTML 再试试？

下面附上 github 的响应中 CSP 的设置。

![network](https://user-images.githubusercontent.com/2580757/67620725-78cdf300-f83c-11e9-8659-4f72fdcc2385.png)

**Comment by AsherSun** [comment]
@qifeng0748 谢谢前辈解惑

**Comment by xiaojue** [comment]
学好英语很重要呀。
